version: '3'

services:
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ./:/tmp/setup
      - ./terraform:/infra
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /infra
    #user: ${UID_GID}
    environment:
      - DATA_DIR="/tmp/localstack"
    extra_hosts:
      - "host.docker.internal:host-gateway"
