version: '3'

services:
  localstack:
    image: localstack/localstack:1.1.0
    entrypoint: [ "/tmp/setup/localstack-setup.sh" ,"docker-entrypoint.sh" ]
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,lambda, cloudwatch
      - LS_LOG=error
      - DATA_DIR="/tmp/localstack"
    ports:
      - '4566:4566'
    volumes:
      - ./:/tmp/setup
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ./:/tmp/setup
      - ./terraform:/infra
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /infra
    #user: ${UID_GID}
    environment:
      - DATA_DIR="/tmp/localstack"
    extra_hosts:
      - "host.docker.internal:host-gateway"
