version: '3'

services:
  localstack:
    image: localstack/localstack:1.1.0
    entrypoint: [ "/tmp/setup/localstack-setup.sh" ,"docker-entrypoint.sh" ]
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,lambda
      - LS_LOG=error
      - DATA_DIR="/tmp/localstack"
    ports:
      - '4566:4566'
    volumes:
      - ./:/tmp/setup