name: opt-out-import integration tests

on:
  push:
    paths:
      - .github/workflows/opt-out-import-test-integration.yml
      - optout/**
  workflow_dispatch:

# Ensure we only have one integration test running at a time
concurrency:
  group: opt-out-export-test-integration

jobs:
  # Deploy first if triggered by push
  deploy:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/opt-out-import-deploy-test.yml

  upload:
    if: ${{ always() }}
    needs: deploy
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./optout
    steps:
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          # Note that we use the lambda role with access to the bucket
          role-to-assume: arn:aws:iam::${{ secrets.TEST_ACCOUNT_ID }}:role/delegatedadmin/developer/ab2d-test-opt-out-import-function
      - name: Upload test file to the BFD bucket
        run: |
          aws s3 cp --no-progress src/test/resources/optOutDummy.txt \
            s3://bfd-test-eft/bfdeft01/ab2d/in/testing.txt

  # TODO Run another job to check database for update, then check bucket for response file
